### ISSUE TITLE
Google Cloud Storage: Getting metadata for a blob that has an entry with `/` in the key throws an exception

### ISSUE THREAD

**Issue by frekw** [googleapis/java-storage#1137]
#### Environment details

1. Google Cloud Storage
2. OS type and version: Debian Stable 11.1
3. Java version: JDK 17
4. storage version(s): `google-cloud-storage` 1.113.9

#### Steps to reproduce

  1. Upload a file to GCS
  2. Add a metadata entry with `/` in the key, such as `v1.namespace/width: 2560`
  3. Attempt to load the metadata via the GCS client resuls in
```
stream error: stream ID 5; PROTOCOL_ERROR; invalid header field name \"x-goog-meta-v1.namespace/width\"
```
even though it loads fine via `gsutil ls -L`

#### Stack trace
```
stream error: stream ID 5; PROTOCOL_ERROR; invalid header field name \"x-goog-meta-v1.namespace/width\"
```

**Comment by frekw** [comment]
Also, according to the docs any ASCII-character should be valid in the keys:

> All fields and their values must consist only of ASCII characters, with the exception of values for x-goog-meta- fields, which may contain arbitrary Unicode values. Note that when setting metadata using the XML API, which sends custom metadata as HTTP headers, Unicode characters are encoded using UTF-8, then url-encoded to ASCII.

**Comment by BenWhitehead** [comment]
Hi @frekw Unfortunately I'm not able to reproduce the error you're seeing with the following code:
```java
  @Test
  void createAndGetObjectWithSlashInMetadataKey() {
    String blobName = "someblob";
    Storage s = StorageOptions.getDefaultInstance().getService();
    BlobId blobId = BlobId.of(myBucketName, blobName);
    BlobInfo blobInfo = BlobInfo.newBuilder(blobId)
        .setMetadata(ImmutableMap.of(
            "v1.namespace/width", "2560"
        ))
        .build();
    Blob createResult = s.create(blobInfo, "Hello World!".getBytes(StandardCharsets.UTF_8));
    Blob getResult = s.get(blobId);
    assertEquals(createResult, getResult);
  }
```

In fact you can see the value present in the response body if you expand the following details.
<details><summary>Response</summary>

I've trimmed out the acls and owner, as they're just noise in this circumstance.

```
HTTP/1.1 200 OK
Content-Length: 3477
Content-Type: application/json; charset=UTF-8
Date: Mon, 08 Nov 2021 20:43:27 GMT
ETag: CPmcjdzQifQCEAE=
Vary: X-Origin
Vary: Origin
Expires: Mon, 08 Nov 2021 20:43:27 GMT

{
  "kind": "storage#object",
  "id": "my-bucket/someblob/1636404207767161",
  "selfLink": "https://www.googleapis.com/storage/v1/b/my-bucket/o/someblob",
  "mediaLink": "https://storage.googleapis.com/download/storage/v1/b/my-bucket/o/someblob?generation=1636404207767161&alt=media",
  "name": "someblob",
  "bucket": "my-bucket",
  "generation": "1636404207767161",
  "metageneration": "1",
  "contentType": "application/octet-stream",
  "storageClass": "STANDARD",
  "size": "12",
  "md5Hash": "7Qdih1MuhjZehB6Sv8UNjA==",
  "crc32c": "/mzx3A==",
  "etag": "CPmcjdzQifQCEAE=",
  "timeCreated": "2021-11-08T20:43:27.770Z",
  "updated": "2021-11-08T20:43:27.770Z",
  "timeStorageClassUpdated": "2021-11-08T20:43:27.770Z",
  "metadata": {
    "v1.namespace/width": "2560"
  }
}
```

</details>

Are there any other details missing compared with your code?

**Comment by frekw** [comment]
Sorry, my bad, this was actually a RPC error that was being bubbled up. It's actually the Go client that's generating the error. I'll try to reproduce it and file an issue there. Super sorry about the noise!

**Comment by BenWhitehead** [comment]
Thanks for confirming, good luck in your investigation with your Go code. If you do still run into issues the best place to open an issue would be over at the [googleapis/google-cloud-go](https://github.com/googleapis/google-cloud-go/issues/new/choose) repo.
