### ISSUE TITLE
add support for OLM Prefix/Suffix

### ISSUE THREAD

**Issue by shaffeeullah** [googleapis/java-storage#1345]
We need to add support for the new LifecycleCondition field options `matchesPrefix` and `matchesSuffix`. Both of these will be a list of strings.

request (internal): [go/prefix-suffix-client-library-request](http://go/prefix-suffix-client-library-request)
nodejs-storage example: https://github.com/googleapis/nodejs-storage/pull/1847

Please wait for my approval before merging/releasing this so we can coordinate around release dates.

**Comment by sydney-munro** [comment]
did initial work for this and will push it to a branch, unfortunately we are blocked on part of the work until automated workflows push model updates to add matchesPrefix and matchesSuffix conditions. see [here](https://github.com/googleapis/google-api-java-client-services/blob/main/clients/google-api-services-storage/v1/1.31.0/com/google/api/services/storage/model/Bucket.java#L1514-L1819)

**Comment by shaffeeullah** [comment]
@sydney-munro is this still blocked?

**Comment by sydney-munro** [comment]
Discovery doc has been updated the the storage client code generation for the fields has been merged. this is now unblocked. Should be able to get a PR out either today or monday.
