### ISSUE TITLE
Make GCS compatible with AWS S3s multiple object delete API

### ISSUE THREAD

**Issue by linzebing** [googleapis/java-storage#1387]
**Is your feature request related to a problem? Please describe.**
We are migrating our AWS S3 code to use GCS. However, the fact that GCS is not compatible with S3's multiple object delete API bothers me, and now I'm deleting objects one at a time, and it's not really ideal.

**Describe the solution you'd like**
I hope GCS can become compatible with S3' multiple object delete API.

**Describe alternatives you've considered**
Currently I'm deleting one object at a time. Another option is, I can leverage `com.google.cloud.storage.StorageBatch`, but that means I need to use GCS's library, and redo all the credentials stuff. Plus, there is no asynchronous API. This defeats the purpose of reusing the S3 code to create a seamless migration.

**Additional context**
N/A

**Comment by BenWhitehead** [comment]
Hi @linzebing, This functionality would require feature work by the GCS backend system.

We will pass along the request so they are aware.

Additionally, it would probably be good to engage with support to ensure this is also surfaced from that avenue.
