### ISSUE TITLE
The links in README.md of the project are broken

### ISSUE THREAD

**Issue by findinpath** [googleapis/java-storage#1399]
As a newbie, I'm going through the README.md of the project to get acquainted with what the library has to offer and check out the sample code.

However most of the links to the examples are outdated and point towards 

https://github.com/googleapis/google-cloud-java/

although the code samples has been moved to the current project.

**Comment by BenWhitehead** [comment]
@JesseLovelace Can you take a look at these URLs, seems like they weren't updated during the migration.

**Comment by JesseLovelace** [comment]
Hey @findinpath, thanks so much for pointing this out! Yeah, I recently moved all the samples to this repo, and it looks like I need to update the links, so I'll get on that.

In the mean time, you can find whatever samples you're looking for in the [Storage Documentation](https://cloud.google.com/storage/docs/how-to)
