### ISSUE TITLE
Broken Link on Documentation 

### ISSUE THREAD

**Issue by abourakba** [googleapis/java-storage#1455]
Hello, 

 On the main https://github.com/googleapis/java-storage 
the link on the line A complete example for creating a blob can be found at [CreateBlob.java](https://github.com/googleapis/google-cloud-java/tree/main/google-cloud-examples/src/main/java/com/google/cloud/examples/storage/snippets/CreateBlob.java). 
is whether broken or has restricted acces. 
Could you please correct acces right or link ? 

Best Regards
Abdou

**Comment by frankyn** [comment]
https://github.com/googleapis/java-storage/issues/1399
