### ISSUE TITLE
Storage: Dependency issue: Could not find androidx.annotation:annotation:1.1.0

### ISSUE THREAD

**Issue by jnizet** [googleapis/java-storage#148]
#### Environment details

1. API: Storage
2. OS: macOS 10.15.2
3. Java version: 1.8.0_152
4. storage version(s): 1.104.0

#### Steps to reproduce

Create a gradle-based project with these (gradle 6.2):

```
repositories {
    mavenCentral()
    jcenter()
}

dependencies {
    implementation("com.google.cloud:google-cloud-storage:1.104.0")
}
```

Build it.

The build fails with

```
Could not find androidx.annotation:annotation:1.1.0.
     Required by:
         project :backend > com.google.cloud:google-cloud-storage:1.104.0 > com.google.api-client:google-api-client:1.30.8
```

Not sure if this dependency should exist in the first place. But if it should exist, then it should also be published to the repositories where google-cloud-storage is published. Or at the very least, the README should indicate if/when the dependency can be excluded and/or which repository to add to be able to use google-cloud-storage

**Comment by suraj-qlogic** [comment]
@jnizet please try below config

```java
repositories {
    google()
    jcenter()
}

dependencies {
    implementation("com.google.cloud:google-cloud-storage:1.104.0")
}
```

**Comment by jnizet** [comment]
@suraj-qlogic  thanks, that works fine. 

But still, I shouldn't have to do that, IMHO. This is why I submitted this issue (which IMHO, is an issue, and not just a question).

Why is a generic Java library dependant on what seems to be, according android-specific annotations? 
If those annotations are supposed to be in the dependencies published on Maven central, why aren't they also published on Maven central?
If the google repo is necessary, why isn't it documented in the README?

**Comment by suushiemaniac** [comment]
I am experiencing the exact same issue, basically +1 everything @jnizet said.

I'm also astonished that this issue occurs when bumping from `1.103` (no error) to `1.104` (error as described above). The minor version bump does not imply to me that `repositories {}` block should be updated.

**Comment by frankyn** [comment]
@chingor13 it looks like a dependency was added into api-client that's only available in Google maven repository.

**Comment by chingor13** [comment]
cc @elharo

**Comment by elharo** [comment]
I'm still not convinced this was a bug, though there is a lot of failure in tools here because it exercised some parts of the Maven pom.xml that weren't well designed and/or correctly implemented.

Regardless, changes have been committed that will avoid this for now. I don't think @chingor13 has released those yet.

**Comment by frankyn** [comment]
@elharo what are the changes users should be waiting for?

**Comment by elharo** [comment]
https://github.com/googleapis/google-api-java-client/pull/1491
