### ISSUE TITLE
Blob.reload() does not work as intuitively expected

### ISSUE THREAD

**Issue by dmitry-fa** [googleapis/java-storage#149]
Documentation for Blob.writer(BlobWriterOption...) recommends the following way to upload information:

```
 byte[] content = "Hello, World!".getBytes(UTF_8);
 try (WriteChannel writer = blob.writer()) {
   try {
     writer.write(ByteBuffer.wrap(content, 0, content.length));
   } catch (Exception ex) {
     // handle exception
   }
 }
```

But doc is silent on how to renew the blob object, which is a bit tricky because neither `blob.reload()` nor `storage.getBlob(blob.getBlobId())` does not help. Behavior varies depending on versioning setting for the bucket.

If versioning is enabled:

Attempt to reload as recommended:
`blob.reload(Blob.BlobSourceOption.generationNotMatch())` causes `StorageException '304 Not Modified'`

`blob.reload()`  returns the same blob.
`storage.get(blob.getBlobId())` returns the same blob (that seems very confusing).
And only `storage.get(blobId)` returns the updated blob.

If versioning is Suspended:
before upload: `blob.getContent()` returns an empty array
After upload: `blob.getContent()` throws `StorageException: 404 Not Found , No such object`
`storage.get(blob.getBlobId())`, `blob.reload()` and `blob.reload(Blob.BlobSourceOption.generationNotMatch())` return null.

And again only storage.get(blobId) returns the updated blob.

**Comment by dmitry-fa** [comment]
For those who want to play around with it:
Setting versioning on a bucket with gsutil:
`#> gsutil versioning set on gs://bucket_versioning_on`
`#> gsutil versioning set off gs://bucket_versioning_off`

The code:
```
package storage;

import com.google.cloud.WriteChannel;
import com.google.cloud.storage.*;
import java.nio.ByteBuffer;

import static java.nio.charset.StandardCharsets.UTF_8;

public class Writer {

    public static void main(String... args) throws Exception {

        Storage storage = StorageOptions.getDefaultInstance().getService();
        String blobName = "my-blob-name";
        String bucketName = "bucket_versioning_off";

        BlobId blobId = BlobId.of(bucketName, blobName);
        byte[] content = "Hello, World!".getBytes(UTF_8);
        BlobInfo blobInfo = BlobInfo.newBuilder(blobId).setContentType("text/plain").build();
        Blob blob = storage.create(blobInfo);
        System.out.println("-- initial --");
        System.out.println(blob);
        System.out.println("size: " + blob.getContent().length);

        try (WriteChannel writer = blob.writer()) {
            writer.write(ByteBuffer.wrap(content));
        }
        System.out.println("\n-- right after upload --");
        System.out.println(blob);
        try {
            System.out.println("content '" + new String(blob.getContent()) + "'");
        } catch (StorageException e) {
            System.out.println("content " + e.getMessage());
        }

        System.out.println("\n-- after blob = blob.reload(Blob.BlobSourceOption.generationNotMatch()) --");

        try {
            blob = blob.reload(Blob.BlobSourceOption.generationNotMatch());
            System.out.println(blob);
        } catch (StorageException e) {
            System.out.println("exception: " + e.getMessage());
            System.out.println("\n-- after blob = blob.reload() --");
            blob = blob.reload();
            System.out.println(blob);
        }

        if (blob != null) {
            System.out.println("\n-- after blob = storage.get(blob.getBlobId()) --");
            blob = storage.get(blob.getBlobId());
            System.out.println(blob);
        }

        System.out.println("\n-- after blob = storage.get(blobId) --");
        blob = storage.get(blobId);
        System.out.println(blob);
    }
}
```

**Comment by dmitry-fa** [comment]
Blob.reload() is just a shortcut method for Storage.get(BlobId). BlobId includes bucket,name and generation. If generation is not specified Storage.get(blobId) returns the latest version. If generation is given and differs from the latest version the output depends on the versioning setting of the bucket: If versioning is enabled Storage.get(BlobId) returns not the latest version, if disabled then null is returned, which means: 'object not found'. Blob.reload() always use generation, so if the content is changed reload() will never return the latest version. Such behavior is not intuitively expected.

Possible fix is to make Blob.reload() to not include generation in the get request.

**Comment by elharo** [comment]
What URL does that sample code come from? It has an issue.

**Comment by dmitry-fa** [comment]
Which sample code do you mean?

**Comment by elharo** [comment]
byte[] content = "Hello, World!".getBytes(UTF_8);
 try (WriteChannel writer = blob.writer()) {
   try {
     writer.write(ByteBuffer.wrap(content, 0, content.length));
   } catch (Exception ex) {
     // handle exception
   }
 }

**Comment by dmitry-fa** [comment]
https://googleapis.dev/java/google-cloud-storage/latest/com/google/cloud/storage/Blob.html#writer-com.google.cloud.storage.Storage.BlobWriteOption...-
