### ISSUE TITLE
outdated links

### ISSUE THREAD

**Issue by eaball35** [googleapis/java-storage#1511]
Original bug filed by jldarrow at b/239093750

Link to `CreateBlob` and `UpdateBlob` are out of date (may be other locations in client still too) - https://github.com/googleapis/java-storage/blob/main/google-cloud-storage/src/main/java/com/google/cloud/storage/package-info.java#L22

**Comment by dandhlee** [comment]
We just got another internal bug filed for this, please take another look whenever you can!
