### ISSUE TITLE
Storage.get(bucketname,filepath) returns null when filename has space (1.103.1,java8)

### ISSUE THREAD

**Issue by sudipbhandari126** [googleapis/java-storage#156]
#### Steps to reproduce

  1. create a file inside a bucket which has space in its name (eg: hotel booking.pdf)
  2. try to download the blob using storage.get(bucket,filepath)

#### Code example

```java
log.info("Attempting to download file {} from bucket {}", filePath,bucketName);
    Blob blob = storage.get(bucketName, filePath);
    if (Objects.isNull(blob)) {
      log.error("file not present for {}", fileName);
      //            throw new FileNotFoundException("file not present for: {}", fileName);
    }
```

#### Stack trace
```
file not present for 'hotel booking.pdf'
```

#### External references such as API reference guides

- ?

#### Any additional information below

Following these steps guarantees the quickest resolution possible.

Thanks!

**Comment by athakor** [comment]
@sudipbhandari126 could you try using the latest release:
https://search.maven.org/artifact/com.google.cloud/google-cloud-storage-parent/1.104.0/pom

**Comment by sudipbhandari126** [comment]
My build is failing for the latest version with the following errror:
```java

Could not find androidx.annotation:annotation:1.1.0
....
Required by:
      project :core > com.google.api-client:google-api-client:1.30.8
```

**Comment by athakor** [comment]
@sudipbhandari126 please check the issue https://github.com/googleapis/java-storage/issues/148

**Comment by sudipbhandari126** [comment]
Great.
Thanks for the quick response.

couple questions:
1. why an additional dependency wasn't bundled?
2. why sudden change while upgrading version that we had to add new repository?

**Comment by athakor** [comment]
cc @elharo
