### ISSUE TITLE
Using %d instead of %s for formating in checkArgument

### ISSUE THREAD

**Issue by runevalle-cognite** [googleapis/java-storage#159]
There are currently being used %d instead of %s in template string to checkArguments in
https://github.com/googleapis/java-storage/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java#L692

This makes the output from precondition failure come out awkwardly.

I guess someone with more routine in getting changes into this codebase can make this fix faster than me.

**Comment by athakor** [comment]
@runevalle-cognite i dont think so we need to add `%s` instead of `%d`, because with the `%d` format specifier, you can use an argument of all integral types including `byte`, `short`, `int`, `long` and `BigInteger`. you can see [here](https://github.com/googleapis/java-storage/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java#L688) argument `position` is `long`.

**Comment by runevalle-cognite** [comment]
@athakor 
Yes, if it had been the standard formater that had been used, %d would have worked, however that is not the case in guava Preconditions.

Part of stack trace that lead to the discovery of this bug:
java.lang.IllegalArgumentException: Position should be non-negative, is %d [-1]"} com.google.cloud.storage.StorageException: java.lang.IllegalArgumentException: Position should be non-negative, is %d [-1] at com.google.cloud.storage.StorageException.translateAndThrow(StorageException.java:74) at com.google.cloud.storage.BlobReadChannel.read(BlobReadChannel.java:141)

Outline of to reproduce: 
- Establish a channel to a google storage bucket.
- channel.seek(-1);
- channel.read(buffer)

Documentation for guava:
https://guava.dev/releases/19.0/api/docs/com/google/common/base/Preconditions.html#checkArgument(boolean,%20java.lang.String,%20java.lang.Object...)

Relevant source code line in the formater that is actually used:
https://github.com/google/guava/blob/master/guava/src/com/google/common/base/Strings.java#L276
