### ISSUE TITLE
Can't obtain info on blob with space in name

### ISSUE THREAD

**Issue by asm0dey** [googleapis/java-storage#166]
Thanks for stopping by to let us know something could be better!

#### Environment details

2. Manjaro 19.0.2
3. Java version: Java 11
4. datastore version(s): 1.102.3

#### Steps to reproduce

1. Create blob with whitespace in it's name: `some/another/white space.txt`
2. Obtain info about it with `storage.get(bucketName, "some/another/white space.txt")`
3. Obtain length from there: NPE occures

While debugging we can find followin error:

```json
{
  "code" : 404,
  "errors" : [ {
    "domain" : "global",
    "message" : "No such object: test-52565030-4e60-11ea-90d4-b3cfcebcc4ca/some/another/white+space.txt",
    "reason" : "notFound"
  } ],
  "message" : "No such object: test-52565030-4e60-11ea-90d4-b3cfcebcc4ca/some/another/white+space.txt"
}

```

Thanks!

**Comment by crwilcox** [comment]
Hi @asm0dey I think this is the storage api.

**Comment by frankyn** [comment]
Hello @asm0dey,

Thanks for filing an issue.

Could you bump your version to at least `1.104.0`. The issue was resolved starting at this version and was tracked here: https://github.com/googleapis/java-storage/issues/121#issuecomment-588604249

Please let me know if you have any issues!

Relabeling as a question.

**Comment by asm0dey** [comment]
Oh, thank you! Didn't see that version is updated. Bump to 105.0 fixed the problem. 
Please, fix documentation on Google Cloud site, I took my version number there. Thank you!

**Comment by frankyn** [comment]
Thanks for pointing that out, I'll make sure to get that updated. Thanks!
