### ISSUE TITLE
Resumable upload should implement truncated exponential backoff when retrying

### ISSUE THREAD

**Issue by bowenshu** [googleapis/java-storage#178]
Thanks for stopping by to let us know something could be better!

**PLEASE READ**: If you have a support contract with Google, please create an issue in the [support console](https://cloud.google.com/support/) instead of filing on GitHub. This will ensure a timely response.

**Is your feature request related to a problem? Please describe.**
What the problem is. Example: I'm always frustrated when [...]

It seems that the current resumable upload implementation will keep retrying with no delays. If the server is already congested, retry will likely make the congestion worse.

**Describe the solution you'd like**
What you want to happen.

Resumable upload should implement truncated exponential backoff when retrying (https://cloud.google.com/storage/docs/exponential-backoff)

**Describe alternatives you've considered**
Any alternative solutions or features you've considered.

**Additional context**
I don't see any obvious exponential backoff logic [here](https://github.com/googleapis/google-api-java-client/blob/21af62a45eb167adcf4d6932b27f9e2b86fc06f3/google-api-client/src/main/java/com/google/api/client/googleapis/media/MediaHttpUploader.java#L407-L483)

**Comment by frankyn** [comment]
Resumable uploads does support truncated exponential backoff. The definition of Jitter may be causing a quirk here and making it look like exponential backoff is not occurring:

> Jitter determines if the delay time should be randomized. In most cases, if jitter is set to true the actual delay time is calculated in the following way:
>
> actualDelay = rand_between(0, min(maxRetryDelay, exponentialDelay))


We may want to disable it automatically, but to close the loop it is supported. 
@bowenshu do you have thoughts on just disabling jitter by default?

To disable [Retry Jitter](http://googleapis.github.io/gax-java/1.8.0/apidocs/com/google/api/gax/retrying/RetrySettings.Builder.html#setJittered-boolean-
```
RetrySettings retrySettings = StorageOptions.getDefaultRetrySettings()
            .toBuilder()
            .setJittered(false)
            .build();

StorageOptions storageOptions = StorageOptions.newBuilder().
            setRetrySettings(retrySettings).
            build();
```

**Comment by frankyn** [comment]
Closing issue as question is resolved per discussion with @bowenshu offline.

A follow-up action is to see if Jitter can be updated to follow a pattern of:

```
exponentialDelay + random_seconds
```
