### ISSUE TITLE
Handle generation numbers in BlobId#{to,from}GsUtilUri

### ISSUE THREAD

**Issue by davidmandle** [googleapis/java-storage#1928]
Unlike `gsutil`, `BlobId#toGsUtilUri` currently ignores a `BlobId`'s generation number, and `BlobId#fromGsUtilUri` doesn't parse generation numbers. It would be nice if, consistent with `gsutil`, `fromGsUtilUri` parsed any generation number in the URI so that references to particular versions of blobs could be made in URI format.

**Comment by jjathman** [comment]
I think this should have been noted as a potentially breaking change and likely created a new API for this usage. In our applications we had application A which is generating the GS URI using version 2.22.0 which now includes the generation in the URL. However, other applications are still using 2.11.x which incorrectly reads the new String.

**Comment by BenWhitehead** [comment]
Apologies for that @jjathman, I'll try and get a fix posted for the next release.

**Comment by BenWhitehead** [comment]
v2.22.1 has been cut which restores the previous behavior to `toGsutilUri` and adds a new method `toGsutilUriWithGeneration` if the generation can be included.

@davidmandle you'll want to switch to using the new method

@jjathman this fix version should now make uris compatible with the v2.11.x series

**Comment by jjathman** [comment]
@BenWhitehead really appreciate it!

**Comment by davidmandle** [comment]
Apologies for the breakage. Thank you for resolving it!
