### ISSUE TITLE
google-cloud-storage: auto-value is included in published version of dependencies

### ISSUE THREAD

**Issue by Ironlink** [googleapis/java-storage#1973]
#### Environment details

version: 2.21.0

#### Steps to reproduce

  1. Inspect pom.xml as found on maven central: https://repo1.maven.org/maven2/com/google/cloud/google-cloud-storage/2.21.0/google-cloud-storage-2.21.0.pom
  2. See that com.google.auto.value:auto-value is listed as a dependency in the compile scope

#### Any additional information below

As can be seen in [com.google.cloud:google-cloud-shared-config](https://github.com/googleapis/java-shared-config/blob/main/pom.xml), this dependency is supposed to be on the javac annotation processor path.

Could this be removed from dependencies in the published version of the pom, as the file is rather large at 4.5 MB? It seems to me that its presence in the final dependencies is not intended.

**Comment by BenWhitehead** [comment]
This is actually flowing into our pom via one of our dependencies (our pom is flattened to level maven dependency resolution quirkiness). I've raised an issue with that library https://github.com/googleapis/gapic-generator-java/issues/1618 where this would need to be addressed. Once fixed there, storage (and all gcp libraries) will get the fix on the next release.

Please follow along there for an idea of progress.
