### ISSUE TITLE
GKE <-> GCS Bucket storage auth problem

### ISSUE THREAD

**Issue by RoysyLee** [googleapis/java-storage#204]
#### Environment details

1. Specify the API at the beginning of the title. For example, "BigQuery: ...").
  GKE, GCS
2. OS type and version: Compute Engine
3. Java version: 1.8
4. storage version(s): 1.106.0

#### Steps to reproduce

  1. GKE deploy java application with storage library's upload
  2. 403 error

#### Code example
[kotlin]

private var storage: Storage = StorageOptions.getDefaultInstance().service
val blobInfo: BlobInfo = storage.create(~~)

(*I just follow example upload code)
#### Stack trace

error code: 403
message: Primary: /namespaces/{ProjectName}-{ProjectId}.svc.id.goog with additional claims does not have storage.objects.create access to {imgUrl}.",

#### Any additional information below

I'm using GKE and GCS.
I made GCS bucket private and give that bucket's storage manage auth to compute engine service account.
When I set my local computer's credentials by compute engine service account' json file, upload is OK.
But in Compute engine(GKE), upload is fail... TT

Log output is
"Primary: /namespaces/{ProjectName}-{ProjectId}.svc.id.goog with additional claims does not have storage.objects.create access to {imgUrl}."

It seems that Compute engine service account is not using for auth.
what is svc.id.goog..?
Help Plz..

thank you for reading my issue!!

**Comment by frankyn** [comment]
Hi @RoysyLee 

Thanks for filing the issue.

Which role did you grant the Compute Engine default service account?

**Comment by RoysyLee** [comment]
I granted "roles/storage.objectAdmin" role to Compute Engine default service account.
So my local server can upload image to private gcs bucket by using that account's auth.
I verified my local server use Compute Engine default service account user's credentials.
when i remove "roles/storage.objectAdmin" from that account, local can't upload image.
But in Compute engine, can't upload whenever.

Log shows
 **"Primary: /namespaces/{ProjectName}-{ProjectId}.svc.id.goog with additional claims does not have storage.objects.create access to {imgUrl}"**

If compute engine use Compute Engine default service account, log's output must be
 **"{SomeId}-compute@developer.gserviceaccount.com does not have storage.objects.create access to {imgUrl}"**

What is "{ProjectName}-{ProjectId}.svc.id.goog"?

**Comment by frankyn** [comment]
I haven't seen this error before either. I suspect it's not associated to your Compute Engine default service account. 

After reviewing: https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity
I suspect you need to look for a service account with `svc.id.goog` in your project.

Could you verify?

**Comment by RoysyLee** [comment]
Thank you!!!
The problem is Workload Identity.
I have to connect k8s Service account to Google service account.
Solved it. I really appreciate it for you! Have a nice day.
