### ISSUE TITLE
Google Cloud Storage library using deprecated javax package

### ISSUE THREAD

**Issue by abhishekshan03** [googleapis/java-storage#2176]
If you run mvn dependency:tree you can see that javax.annotation-api is being pulled 
[INFO] +- com.google.cloud:google-cloud-storage:jar:2.26.1:compile
[INFO] |  +- javax.annotation:javax.annotation-api:jar:1.3.2:compile

javax package is not compliant with Jakarta platform. Please release google-cloud-storage:jar which is Jakarta platform compliant.

**Comment by sydney-munro** [comment]
looks like we are pulling this in from 

```
com.google.api:api-common:jar:2.15.0:compile
[INFO] |  \- javax.annotation:javax.annotation-api:jar:1.3.2:compile
```

**Comment by sydney-munro** [comment]
I will create an issue in their repository.

**Comment by sydney-munro** [comment]
closing this issue in favor of the issue in sdk-platform-java.

**Comment by suztomo** [comment]
@abhishekshan03 I posted question in https://github.com/googleapis/sdk-platform-java/issues/1938. Shall we continue discussion there?
