### ISSUE TITLE
BlobReadChannel read trows a non-IOException

### ISSUE THREAD

**Issue by agrinh** [googleapis/java-storage#219]
Couldn't find this discussed anywhere and thought it belonged here, I hope you agree, please let me know otherwise.

[`BlobReadChannel.read`](https://github.com/googleapis/java-storage/blob/035ae2ad876fc9d17f86449d17f675000831b185/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannel.java#L114) is annotated with `@throws IOException` which fits the interface and expected behaviour with nio (e.g. I get the expected `IOException` on read in the standard `ReadableBytesChannel` interface and in an input stream created with `Channels.newInputStream`)

However, at least one of the [current exceptions](https://github.com/googleapis/java-storage/blob/035ae2ad876fc9d17f86449d17f675000831b185/google-cloud-storage/src/main/java/com/google/cloud/storage/BlobReadChannel.java#L136) thrown is `StorageException`, which is *not* an `IOException`, forcing users to know that this particular `ReadbleBytesChannel` throws another exception.

Could the exceptions thrown here be modified to inherit from `IOException` instead?

**Comment by frankyn** [comment]
Hi @agrinh,

Thanks for filing this issue. Looks like this has been an issue for a while now. I think it makes sense to update the exception type, but haven't investigated the implications of making such a change. 

How often does this occur?

**Comment by dmitry-fa** [comment]
What about introducing new StorageIOException extending IOException?

**Comment by frankyn** [comment]
If it's a bug for the contract to return StorageException, then it should be updated to an IOException to reduce confusion. It also avoids the need to support another Exception class.

Additionally, the method has `throws IOException` so it's a known checked exception for end-users.

**Comment by dmitry-fa** [comment]
The thrown StorageException used to contain the extra code, fortunately, in case of BlobReadChannel.read() this code is UNKNOWN_CODE, so yes we could safely replace StorageException with IOException without introducing a new exception class.

I'll take care of this.

**Comment by frankyn** [comment]
Thanks @dmitry-fa !

**Comment by agrinh** [comment]
Thanks, that sounds great! 

Also, @frankyn sorry for not getting back to you sooner, looks like you don't need any further input now.
