### ISSUE TITLE
Feature request : get only metadata, not the blob itself

### ISSUE THREAD

**Issue by julientard** [googleapis/java-storage#225]
Hey guys, 

I'm just starting to use GCP and GCS with the java sdk.
I would like to check metadata of a object, without downloading all the object. 

It seems to be possible with the API, with the query param `alt=json`.

Maybe I miss something but i didn't find this possibility with the SDK.

It would be great to have this option available within the SDK.

**Comment by dmitry-fa** [comment]
`Blob Storage.get(Blob blobId) ` returns the Blob instance, which contains just information about the blob, not the content of the blob.

**Comment by julientard** [comment]
Great thank you !
I didn't realize the Blob object encapsulate the API calls to read the content. My bad.
