### ISSUE TITLE
Google Cloud Storage | CRC32c of large files.

### ISSUE THREAD

**Issue by Tiozi** [googleapis/java-storage#25]
Hello,

I'm developing a service to upload files between 1GB and 2GB to Google Cloud Storage.

There's a way to calculate the CRC32hash while i'm writing the stream in the WriteChannel ?

The problem is that always i need to calculate the hash of the whole file before create the blobInfo with the calculated hash.

Here is my current code.

![Hash](https://user-images.githubusercontent.com/49068263/66048940-da7e9400-e500-11e9-812d-b59e5453fdd8.JPG)

Thanks everyone!

**Comment by dmitry-fa** [comment]
@Tiozi I hope the question is answered, if you need more details please provide more info.
