### ISSUE TITLE
Checksum verification when uploading file to cloud storage not working - version 2.36.1

### ISSUE THREAD

**Issue by ihudedi** [googleapis/java-storage#2528]
Hi,
I am trying to set md5 verification when I upload file as follows:
 BlobId blobId = BlobId.of(bucketName, filePath);
        BlobInfo.Builder blobInfoBuilder = BlobInfo.newBuilder(blobId);
        blobInfoBuilder .setMd5FromHexString(md5Hex);
        BlobInfo blobInfo = blobInfoBuilder.build();
        WriteChannel writeChannel = getWriteChannel(blobInfo);
        writeChannel.setChunkSize(gcsChunkSize);
        OutputStream gcsOutputStream = Channels.newOutputStream(writeChannel);
        gcsOutputStream .write();
       gcsOutputStream.close();

Any md5 hex I am giving doesn't produce an error.
Does the server verify this MD5?
Thanks,
Itay

**Comment by ddelgrosso1** [comment]
Hi @ihudedi from the looks of it you need to specify a `BlobWriteOption` when retrieving the write channel. See the [docs here](https://cloud.google.com/java/docs/reference/google-cloud-storage/latest/com.google.cloud.storage.Storage#com_google_cloud_storage_Storage_writer_com_google_cloud_storage_BlobInfo_com_google_cloud_storage_Storage_BlobWriteOption____). 

Additionally, we recommend using CRC32C as opposed to MD5.

**Comment by BenWhitehead** [comment]
What @ddelgrosso1 says is correct. The option must be passed when calling `Storage#writer`.

For a full code sample, take a look at our integration tests that verify checksum validation works via positive and negative cases: https://github.com/googleapis/java-storage/blob/b84654e79ee53087badc0315ea3fb2d1b0b9ca57/google-cloud-storage/src/test/java/com/google/cloud/storage/it/ITObjectChecksumSupportTest.java#L209-L214
