### ISSUE TITLE
docs: label legacy Storage Classes in documentation

### ISSUE THREAD

**Issue by frankyn** [googleapis/java-storage#254]
Cloud Storage storage classes are listed in [library javadocs](https://googleapis.dev/java/google-cloud-storage/latest/com/google/cloud/storage/StorageClass.html) and they need to be updated to label legacy storage with [current guidance](https://cloud.google.com/storage/docs/storage-classes#legacy) on using "STANDARD" for new buckets.

Legacy Storage Classes:

* DURABLE_REDUCED_AVAILABILITY
* MULTI_REGIONAL
* REGIONAL

@dmitry-fa can you pick up this change?

**Comment by dmitry-fa** [comment]
@frankyn yes, I'll take care of it.
