### ISSUE TITLE
Google Cloud Storage - java sdk - retrySettings does not recover network errors

### ISSUE THREAD

**Issue by Eliyahu-Machluf** [googleapis/java-storage#26]
I'm trying to configure my 'google cloud storage' client to use internal retries.
I added configuration for retrySettings like this:

        RetrySettings retrySettings = RetrySettings
                .newBuilder()
                .setMaxAttempts(50)
                .setInitialRetryDelay(Duration.ofSeconds(10))
                .setRetryDelayMultiplier(1.5)
                .setMaxRetryDelay(Duration.ofSeconds(20))
                .build();
        storage = StorageOptions.newBuilder().setRetrySettings(retrySettings).setCredentials(credentials).build().getService();
    ....

I then tried to upload a 500MB file, and during the upload process, disconnect the network.
I expected the upload to be retried for at least 10 minutes, however I got an error almost immediately.

I have some questions:
1. Am I missing something? Does the code above look OK?
2. Is there a way to turn on debug information for the java client, so I can see at log file what occur?
3. I did not find an appropriate java tutorials for google cloud storage java SDK, only some code samples. Is there a good tutorial for the java SDK?

**Comment by dmitry-fa** [comment]
@Eliyahu-Machluf , thanks for your questions,

Retrying mechanism is designed to handle timeouts from data transferring, network issues or access denied problems are out of scope of its responsibility.
https://cloud.google.com/storage/docs/gsutil/addlhelp/RetryHandlingStrategy


> 1.   Am I missing something? Does the code above look OK?

Your code looks correct, but it won't protect you from temporary network disconnections.

> 2.  Is there a way to turn on debug information for the java client, so I can see at log file what occur?

Logging for your app can be turned:
  https://cloud.google.com/java/getting-started/logging-application-events

> 3. I did not find an appropriate java tutorials for google cloud storage java SDK, only some code samples. Is there a good tutorial for the java SDK?

I can recommend the following links:

language independent:
    https://cloud.google.com/storage/docs/concepts
    https://cloud.google.com/storage/docs/how-to
java specific:
   https://cloud.google.com/java/getting-started/using-cloud-storage
   https://googleapis.dev/java/google-cloud-clients/latest/com/google/cloud/storage/package-summary.html

**Comment by Eliyahu-Machluf** [comment]
Thanks.
