### ISSUE TITLE
Convert StorageImplTest from EasyMock to Mockito

### ISSUE THREAD

**Issue by dmitry-fa** [googleapis/java-storage#270]
Google requires new tests to use Mockito even if existing tests use EasyMock.
It's really hard to use two frameworks within a single test because setUp/tearDown methods invoked before and after each test perform some framework specific actions.
It's not required to convert all tests to Mockito, but the overhead of supporting both frameworks can be higher than the effort to convert existing tests.
In case of StorageImplTest, there will be many new tests developed for new Storage features, so it worths to convert these tests.

**Comment by elharo** [comment]
You can always create a new test class that uses Mockito. There's no requirement that we only have one test class per model class.

**Comment by dmitry-fa** [comment]
Two test classes per model class will lead to code duplication. Perhaps the right way to go is:
- rename StorageImplTest.java to StorageImplTestLegacy.java
- create new StorageImplTest.java using Mockito
- start moving tests from legacy to modern form by portion

**Comment by meredithslota** [comment]
It looks like the bulk of this work is already done in the linked PRs — @frankyn is this ok to close out?

**Comment by frankyn** [comment]
Hi @meredithslota this is still an issue to move away from EasyMock.

**Comment by frankyn** [comment]
Passing it over to @JesseLovelace who had been working on this issue from last fixit
