### ISSUE TITLE
feat: Add Mockito dependency

### ISSUE THREAD

**Issue by dmitry-fa** [googleapis/java-storage#283]
Google requires new tests to use Mockito even if existing tests use EasyMock.

**Comment by frankyn** [comment]
We will need to add an AI to address existing tests as well.

**Comment by dmitry-fa** [comment]
@frankyn, do you mean #270 ?

**Comment by frankyn** [comment]
If it was relabeld to `Update EasyMock tests to use Mockito` feature request. Yes!
