### ISSUE TITLE
The registerSpanNamesForCollection() method is deprecated in HttpStorageRpcSpans

### ISSUE THREAD

**Issue by suraj-qlogic** [googleapis/java-storage#287]
The **registerSpanNamesForCollection()** method is deprecated since **OpenCensus-0.18.**
```
[WARNING] /F:/google-cloud-repository/java-storage/google-cloud-storage//src/main/java/com/
google/cloud/storage/spi/v1/HttpStorageRpcSpans.java:[155,9] registerSpanNamesForCollection
(java.util.Collection<java.lang.String>) in io.opencensus.trace.export.SampledSpanStore has
been deprecated
```

**Comment by frankyn** [comment]
What's the non-deprecated way?

**Comment by suraj-qlogic** [comment]
Hi @frankyn,EndSpanOptions#getSampleToLocalSpanStore() is used to remove registerSpanNames ForCollection() deprecated method.
I am planning to go ahead EndSpanOptions#getSampleToLocalSpanStore() to remove registerSpan NamesForCollection() deprecated method.

**For More information**: https://github.com/census-instrumentation/opencensus-java/blob/2a17c8482ffb04540ea4ac0a5f746ad8d536c996/api/src/main/java/io/opencensus/trace/export/SampledSpanStore.java#L102-L112
