### ISSUE TITLE
Does versioned listing return in order?

### ISSUE THREAD

**Issue by lwshuo** [googleapis/java-storage#304]
when I do 
`Page<Blob> blobs = bucket.list(Storage.BlobListOption.versions(true));`
is the results ordered in anyway?

Thanks!

**Comment by frankyn** [comment]
Hi @lwshuo,

The cloud storage List request is ordered in lexographical order based on the name in the response. Cloud Storage Documentation is being updated to call this ordering out better but have confirmed with the backend team. 

If this does not answer your question please feel free to reopen.
