### ISSUE TITLE
Support reading gzip files as-is with google-cloud-storage?

### ISSUE THREAD

**Issue by ZxMYS** [googleapis/java-storage#321]
**Is your feature request related to a problem? Please describe.**
https://cloud.google.com/storage/docs/transcoding describes that if I upload a file with content-encoding set to gzip, it's automatically decompressed for read, unless I specify `Accept-Encoding: gzip` in my read request. However, I can't find an obvious way to set the header with `google-cloud-storage`, so I wonder if it supports to do so, or if there's another way to read gzipped file as is with the library. 
Note that sometimes I do want to get the file back unzipped, so I want to keep setting content-encoding to gzip when I save the object.

 **Describe the solution you'd like**
`google-cloud-storage` should provide an option to set Accept-Encoding when downloading a blob. For example, make it an option of `Blob.downloadTo` maybe.

**Comment by athakor** [comment]
@ZxMYS try this to read the compressed blob 

```javascript
import com.google.cloud.ReadChannel;
import com.google.common.io.BaseEncoding;
import com.google.common.io.ByteStreams;
import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.util.zip.GZIPInputStream;

import static java.nio.charset.StandardCharsets.UTF_8;
import static org.junit.Assert.assertArrayEquals;

public class ReadCompressedBlob {
    private static final String BUCKET = "bucket-name";
    private static final String BLOB_STRING_CONTENT = "Hello Google Cloud Storage!";
    private static final byte[] COMPRESSED_CONTENT = BaseEncoding.base64().decode("H4sIAAAAAAAAAPNIzcnJV3DPz0/PSVVwzskvTVEILskvSkxPVQQA/LySchsAAAA=");

    @Test
    public void testReadCompressedBlob() throws IOException {
        Storage storage = StorageOptions.getDefaultInstance().getService();
        String blobName = "test-read-compressed-blob";
        BlobInfo blobInfo =
                BlobInfo.newBuilder(BlobId.of(BUCKET, blobName))
                        .setContentType("text/plain")
                        .setContentEncoding("gzip")
                        .build();
        Blob blob = storage.create(blobInfo, COMPRESSED_CONTENT);
        try (ByteArrayOutputStream output = new ByteArrayOutputStream()) {
            try (ReadChannel reader = storage.reader(BlobId.of(BUCKET, blobName))) {
                reader.setChunkSize(8);
                ByteBuffer buffer = ByteBuffer.allocate(8);
                while (reader.read(buffer) != -1) {
                    buffer.flip();
                    output.write(buffer.array(), 0, buffer.limit());
                    buffer.clear();
                }
            }
            assertArrayEquals(
                    BLOB_STRING_CONTENT.getBytes(UTF_8), storage.readAllBytes(BUCKET, blobName));
            assertArrayEquals(COMPRESSED_CONTENT, output.toByteArray());
            try (GZIPInputStream zipInput =
                         new GZIPInputStream(new ByteArrayInputStream(output.toByteArray()))) {
                assertArrayEquals(BLOB_STRING_CONTENT.getBytes(UTF_8), ByteStreams.toByteArray(zipInput));
                System.out.println(ByteStreams.toByteArray(zipInput));
            }
        }
    }
}
```

**Comment by ZxMYS** [comment]
@athakor thanks, this works! Its performance seems to be worse than blob.getContent but with a bigger buffer it looks ok. I'm unblocked.

It would be great if things like "ReadChannel skips transcoding" and "google api transportation layer gzips requests and responses (right?)" are documented, and if Blob's read methods have some control over the headers or the transcoding behavior.

**Comment by frankyn** [comment]
Hi @ZxMYS,

Apologies for the delay. This might be a bug that we are trying to address in other libraries.

The library does send a header of `Accept-Encoding: gzip`. 
What is the content-type that you're using for the object?

**Comment by ZxMYS** [comment]
Oh, if the library does that it means the library also does unzipping somewhere after it gets response? When I read the bytes they were unzipped.

My content types include `text/x-python` and `application/x-ipynb+json`.

**Comment by frankyn** [comment]
Could you try, "application/octet-stream"?

**Comment by frankyn** [comment]
Any luck on the last comment @ZxMYS?, just checking in.

**Comment by ZxMYS** [comment]
Hi, I was able to fix the issue with the above code so my issue has been resolved.
I need to set proper content types on my objects, so even if `application/octet-stream` works it doesn't fit my requirements.

**Comment by frankyn** [comment]
I'm leaving this open until we get a better solution. Thanks for clarifying @ZxMYS

**Comment by oripwk** [comment]
Hi,

We're hitting this issue. The GCS Java client will always return a decompressed file if the file is a `gzip` and has Content-Encoding of `gzip`. We do not control the Content-Encoding headers and our client always gets a decompressed file.

The workaround provided is too hacky for us to use. We are concerned that too much data is sent on the wire because it is getting decompressed on Google's servers.

Please advice.

**Comment by frankyn** [comment]
Hi @oripwk,

If you need the compressed object you'll need to remove content-encoding: gzip in Object metadata. It's a known issue in the GCS API: https://cloud.google.com/storage/docs/transcoding#gzip-gzip

PLMK if this answers your question.

**Comment by oripwk** [comment]
@frankyn unfortunately we have no control over the existing objects.

From [the docs](https://cloud.google.com/storage/docs/transcoding#decompressive_transcoding):
> there are two ways to prevent decompressive transcoding from occurring […] If the request for the object includes an Accept-Encoding: gzip header.

So I believe it's only a matter of changing the Java client to include this header. Is this a planned feature?

**Comment by frankyn** [comment]
Hi @oripwk,

The library does supply `Accept-Encoding: gzip` header, but is not respected for doubly-compressed objects, e.g. gzip'd `image/jpeg` file for example. It is respected for content-type `text/plain`. 

This the quirk that's documented in the section linked. 

We are looking at potential solutions but as of right now this is a known friction point.

By chance, could you give me more background on how you're relying on these objects and why you need the decompressed version?

Thank you for your patience!

**Comment by oripwk** [comment]
We use the latest Java library version and our objects are not doubly-compressed (i.e. it is gzipped text or binary), and for some reason, using the `.get` method sends back a decompressed object (after invoking the `.getContext()` method).

However, using `gsutil cat` _does_ return a compressed version.

The Content-Type of the objects is `application/json` and `application/octet-stream` by the way.

**Comment by frankyn** [comment]
Thanks @oripwk, it might be a different issue*

Do you have permission to share the GCS object metadata in this thread (if no, please send it to coderfrank@google.com)?

**Comment by oripwk** [comment]
Hi, here's the metadata:

```
    Creation time:          Mon, 26 Oct 2020 16:04:56 GMT
    Update time:            Mon, 26 Oct 2020 16:04:56 GMT
    Storage class:          STANDARD
    Cache-Control:          max-age=1800
    Content-Encoding:       gzip
    Content-Length:         9150
    Content-Type:           application/json
    Hash (crc32c):          TIFQAA==
    Hash (md5):             tdQ+Y0yQNc6FK1q5dzjt4g==
    ETag:                   CLDhv7vR0uwCEAE=
    Generation:             1603728296636592
    Metageneration:         1
```

**Comment by frankyn** [comment]
Hi @oripwk,

So when you download this file using gsutil it will work fine, but won't using this library. 

Given it's a compressible type `application/json` it should respect `Accept-Encoding: gzip`.

Debugging the Java client, but confirmed that data is compressed when passing `Accept-Encoding: gzip` for this case of `application/json` + contentEncoding: gzip.

**Comment by frankyn** [comment]
We will need to introduce a new option to disable decompression in the Java client.

To disable decompress:
```
getRequest.setReturnRawInputStream(true);
```

I'll work on a PR and send it for review.

**Comment by frankyn** [comment]
Hi @oripwk,

I found  a quirk in the library and will need to address this correctly when I have more bandwidth available.

Here's a solution you can use now:
```java
    Storage storage = StorageOptions.getDefaultInstance().getService();
    // The name for the new bucket
    String bucketName = "bucket-name";  // "my-new-bucket";
    String blobName = "object-name";
    // Get Object metadata
    Blob blob = storage.get(BlobId.of(bucketName, blobName));

    // Allocate buffer based on Object Size
    ByteBuffer bf = ByteBuffer.allocate(blob.getSize().intValue());
 
    // Download data
    ReadChannel channel = storage.reader(BlobId.of(bucketName, blobName));
     
    // Download data into ByteBuffer 
    channel.read(bf);
```

For future me:
1. Object needs contentEncoding: gzip and compressible type `application/json`.
1. Blob.downloadTo() and BlobReadChannel both disable automatic content decoding.

Method to validate correctness:

```java
@Test
public void testUncompressedWithReader() throws IOException {
    Storage storage = StorageOptions.getDefaultInstance().getService();
    String bucketName = "anima-frank";  // "my-new-bucket";
    Blob blob = storage.get(BlobId.of(bucketName, "test.json"));
    HashFunction crc32c = Hashing.crc32c();
    ReadChannel channel = storage.reader(BlobId.of(bucketName, "test.json"));
    ByteBuffer bf = ByteBuffer.allocate(blob.getSize().intValue());
    channel.read(bf);
    HashCode hash = crc32c.hashBytes(bf.array());

    byte[] hashBytes = hash.asBytes();
    for (int i = 0; i < hashBytes.length/2; i++) {
      byte tmp = hashBytes[i];
      hashBytes[i] = hashBytes[hashBytes.length-i-1];
      hashBytes[hashBytes.length-i-1] = tmp;
    }
    String hashStr = Base64.encodeBase64String(hashBytes);
    // Verify Object Stored in GCS crc32c and local crc32c of downloaded data are the same.
    assertEquals(blob.getCrc32c(), hashStr);
}
```

**Comment by tritone** [comment]
Discussed this with @frankyn -- we would probably just want to implement this as a flag to `blob.downloadTo` and not change the existing default behavior (as that could break users relying on it).

**Comment by oripwk** [comment]
When is this going to be released?
