### ISSUE TITLE
Allow Signing Policy Document

### ISSUE THREAD

**Issue by thihara** [googleapis/java-storage#39]
The current SDK doesn't support signing policy documents, only signing URLs.

See: https://cloud.google.com/storage/docs/xml-api/post-object#policydocument

Since signed URLs doesn't support limiting the size of the uploaded file, signing policy documents is a much needed feature.

**Comment by athakor** [comment]
closing this issue as it's already being tracked [here](https://github.com/googleapis/java-storage/issues/88)
