### ISSUE TITLE
Expose the zoneAffinity and zoneSeparation field of Bucket class

### ISSUE THREAD

**Issue by suraj-qlogic** [googleapis/java-storage#408]
Expose the ```zoneAffinity``` and ```zoneSeparation``` field of  ```com.google.api.services.storage.model.Bucket``` class.

- [ ] [zoneAffinity](https://github.com/googleapis/google-api-java-client-services/blob/b39bb16a44aa99647d56b39054817ee6493ef8f5/clients/google-api-services-storage/v1/1.30.1/com/google/api/services/storage/model/Bucket.java#L251)
- [ ] [zoneSeparation](https://github.com/googleapis/google-api-java-client-services/blob/b39bb16a44aa99647d56b39054817ee6493ef8f5/clients/google-api-services-storage/v1/1.30.1/com/google/api/services/storage/model/Bucket.java#L258)

./cc @frankyn

**Comment by frankyn** [comment]
Please hold on this as it's not been raised as a request from the service team.
