### ISSUE TITLE
Range header in uploads confusing

### ISSUE THREAD

**Issue by fstab** [googleapis/java-storage#422]
An example range header for the last chunk when uploading an object looks like this:

```
bytes 2621440-2867199/2867200
```

This is confusing, because the first two numbers are 0-based (bytes 2621440-2867199) while the last number is 1-based (out of 2867200 bytes). You'd think that the last byte is missing.

https://github.com/googleapis/java-storage/blob/117f092010ac2218adbe38cf0b9d1e48e7c7e786/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpc.java#L760

**Comment by dmitry-fa** [comment]
The range stands for the Content-Range that includes indices, the last number shows the Content-length.
Another example: https://cloud.google.com/storage/docs/performing-resumable-uploads#upload-file
