### ISSUE TITLE
Passing RSA wrapped CSEK not possible

### ISSUE THREAD

**Issue by bobocu** [googleapis/java-storage#45]
Using the google-cloud-storage api I've no possibilities to define that the passed AES256 Key is RSA wrapped.

`
Storage.BlobWriteOption blobWriteOption = Storage.BlobWriteOption.encryptionKey(str);
Storage.BlobTargetOption blobTargetOption = Storage.BlobTargetOption.encryptionKey(str);
`
Using a RSA wrapped key causes a "Bad Request"

_{
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "customerEncryptionKeyFormatIsInvalid",
    "message": "Missing an encryption key, or it is not base64 encoded, or it does not meet the required length of the encryption algorithm.",
    "extendedHelp": "https://cloud.google.com/storage/docs/encryption#customer-supplied_encryption_keys"
   }
  ],
  "code": 400,
  "message": "Missing an encryption key, or it is not base64 encoded, or it does not meet the required length of the encryption algorithm."
 }
}_

Thanks!
Boris

**Comment by dmitry-fa** [comment]
The following links describe handling CSEK in detail:

[Customer-Supplied Encryption Keys](https://cloud.google.com/security/encryption-at-rest/customer-supplied-encryption-keys/)
[Customer-supplied encryption keys](https://cloud.google.com/storage/docs/encryption/customer-supplied-keys)
[Data encryption options](https://cloud.google.com/storage/docs/encryption#customer-supplied_encryption_keys)

The summary:
Cloud Storage allows you to set customer-supplied encryption keys on **individual objects**. You cannot set a default customer-supplied encryption key for a bucket.
Raw CSEK is stored in the Storage **system memory** and never saved on the Storage device.
I don't any reason for Storage to support wrapping the raw CSEK

For Computer Engine the raw CSEK is combined with a per-persistent disk cryptographic nonce to generate a CSEK-derived key, which is stored in the database:
https://cloud.google.com/security/encryption-at-rest/customer-supplied-encryption-keys/#compute_engine

So, Computer Engine supports public-key wrapped CSEK (optional-RSA key wrapping)

I believe this issue could be closed.
