### ISSUE TITLE
Need a test framework for Storage RPC tests

### ISSUE THREAD

**Issue by dmitry-fa** [googleapis/java-storage#450]
Google requires to cover all new code and all changes in the code by tests. The majority of the Storage code is covered by unit tests, but not `com.google.cloud.storage.spi.v1.HttpStorageRpc`. Testing of  `HttpStorageRpc` is a bit tricky, so having a framework allowing us to write laconic tests for RPC would help to meet the Google requirements.

// cc @frankyn

**Comment by BenWhitehead** [comment]
As of today, the majority of retry related (ITRetryConformanceTest.java) and option mapping related behavior validation (ITOptionRegressionTest.java) are covered by other tests. As such, we're not going to spend time to develop a test framework for only HttpStorageRpc. Instead we will focus on testing the higher level Models and Storage implementations which we steer our customers toward.
