### ISSUE TITLE
User agent library version is not being tracked correctly.

### ISSUE THREAD

**Issue by frankyn** [googleapis/java-storage#451]
User-agent does not have library version:

```
User-Agent: gcloud-java/ Google-API-Java-Client/1.30.10 Google-HTTP-Java-Client/1.36.0 (gzip)
x-goog-api-client: gl-java/11.0.7 gdcl/1.30.10 linux/5.6.14
Content-Type: application/json; charset=UTF-8
Content-Encoding: gzip
```

Should be:

```
User-Agent: gcloud-java/1.xx.x Google-API-Java-Client/1.30.10 Google-HTTP-Java-Client/1.36.0 (gzip)
```

@dmitry-fa do you have cycles to look at this issue?

**Comment by dmitry-fa** [comment]
@frankyn I managed to reproduce the problem if the Storage client is running from IDE. My question: how do you run the Storage client which issues incorrect header?

**Comment by dmitry-fa** [comment]
@frankyn I think this is not a bug.

The following nano application prints the string to be inserted into the UserAgent header:

```
import com.google.cloud.storage.StorageOptions;

public class UserAgent {
  public static void main(String... args) throws Exception {
    System.out.println(StorageOptions.newBuilder().build().getApplicationName());
  }
}
```

Being inserted into the Storage project and run from Intellij Idea  this code prints:
```gcloud-java/```

The same code being inserted into another project depending on the Storage prints:
```gcloud-java/1.110.0```


The library version is exracted by the following code:
```
  public static String getLibraryVersion(Class<?> libraryClass) {
    String version = libraryClass.getPackage().getImplementationVersion();
    return version != null ? version : "";
  }
```
 `libraryClass.getPackage().getImplementationVersion()` reads the version from the manifest stored in the the library jar file. Being run from an IDE the classes of the project are loaded not from the jar, but from the `classes/` dir where there is no manifest file,  as the result no version.
Classes for dependencies are loaded from jars and they have the version available.

**Comment by frankyn** [comment]
Gotcha, I was seeing this in Intellij, thanks for digging this up. It's working as expected in this case. Definitely got confused on my end.

**Comment by dmitry-fa** [comment]
@frankyn you are always welcome :) nice bug, I love such :)
