### ISSUE TITLE
Add ability to batch Storage.create() requests

### ISSUE THREAD

**Issue by yihanzhen** [googleapis/java-storage#480]
Porting over an old issue in google-cloud-java for some attention: https://github.com/googleapis/google-cloud-java/issues/2351

**Comment by athakor** [comment]
@janaton Thanks for the raising this FR but Unfortunately, the back-end API [doesn't support batching "media" operations](https://cloud.google.com/storage/docs/json_api/v1/how-tos/batch), which means we don't support it either.

```
* Note: Currently, Google Cloud Storage does not support batch operations for media,
  either for upload or download.
```

**Comment by janaton** [comment]
@athakor Thank you very much for your fast feedback. 

It is a bit unfortunate that batch operations are not supported. For sure, we can speed up object upload/download by spanning multiple threads but there is still large overhead with each http request :/ (especially when we deal with small objects). Would be really great to have this feature in the near future :). Thanks for your time and consideration to add this FR on the TODO list

**Comment by athakor** [comment]
>Would be really great to have this feature in the near future :)

I cant promise you because i am not sure about this. 

@frankyn  do we have any plan to add this kind of feature in future?

**Comment by frankyn** [comment]
Apologies for the delay. I'll relay this request to the GCS team but there is not plan right now to introduce Object Insert into batch requests. The closest request we have is parallel uploads but is not yet prioritized. 

I'm going to close this issue because it's a backend request.
