### ISSUE TITLE
Cloud Storage: Unable to get blobs with space in their name after upgrading to 1.103.0

### ISSUE THREAD

**Issue by zeev-lilt** [googleapis/java-storage#53]
1. API: Cloud storage
2. OS type and version: OSX
3. Java version: 1.8.0_161
4. storage version(s): 1.103.0

#### Steps to reproduce

  1. Upload a blob that contains a space in its name.
  2. Try to `get` it.

#### Code example

```java
Storage gcs = StorageOptions.getDefaultInstance().getService();
gcs.get("my_bucket", "my blob")
// returns null
```

#### Any additional information below
This works in version `1.102.0` but returns null in `1.103.0`. 
I've tried replacing the space with `%20` or `+`, but that didn't work either.

**Comment by dmitry-fa** [comment]
Yes, this functionality is broken. 
The issue: https://github.com/googleapis/java-storage/issues/57

**Comment by elharo** [comment]
Tracking in #57

**Comment by elharo** [comment]
FYI, this is believed to be completely fixed in the current versions of the relevant libraries that you get with libraries-bom 4.0.0. If anyone still sees this with the *latest versions of all libraries*, please reopen this bug and @ me.

**Comment by dmitry-fa** [comment]
@elharo No, it doesn't work with libraries-bom 4.0.0

Simple code to reproduce:
```
package storage;
import com.google.cloud.storage.*;
public class Spaces {
    public static void main(String... args) throws Exception {
        String bucketName = "bucket_generation_signed";
        String blobName = "1 2";
        byte[] content = "Hello world".getBytes("utf8");
        StorageOptions.getDefaultInstance().getService().create(BlobInfo.newBuilder(bucketName, blobName ).build(), content);
        System.out.println("sent: " + content.length);
        Storage s = StorageOptions.getDefaultInstance().getService();
        byte[] read = s.readAllBytes(bucketName, blobName);
        System.out.println("read: " + read.length);
    }
}
```

Exception in thread "main" com.google.cloud.storage.StorageException: 404 Not Found
No such object: bucket_generation_signed/1+2

**Comment by dmitry-fa** [comment]
@elharo  #57 is still open, I don't think we need to reopen this one.
