### ISSUE TITLE
Google Cloud Logging/Stackdriver doesn't include request ID field 

### ISSUE THREAD

**Issue by ihsanhaikalz** [googleapis/java-storage#530]
I found it very interesting that the log from Google Cloud Logging/Stackdriver monitoring activities in my Bucket does not have the request ID. In Google Storage access log it has the request ID of any activities happening in the Bucket. It would be nice if the log from the Stackdriver has request ID field that can be correlated to the Google Storage access log.

**Comment by frankyn** [comment]
Thanks @ihsanhaikalz, i'll forward this feature request to the GCS backend team. I won't be able to give a timeline or if it will be implemented. For now closing this issue.
