### ISSUE TITLE
Storage: delete methods do not remove files with a whitespace in the name

### ISSUE THREAD

**Issue by mindtraveller** [googleapis/java-storage#538]
#### Environment details

1. OS type and version: macOS Catalina 10.15.6 (19G2021)
2. Java version: 11; Kotlin version: 1.3.41;
3. Storage version(s): 1.110.0 (1.106.0, 1.112.0)

#### Steps to reproduce

  1. Upload file to the `directory` folder with whitespace in the name e.g. `some name.txt`; 
  2. Try to remove it using any `delete` method (e.g. `blob.delete`, `storage.delete(blobId)` etc.);
  3. File is not removed;

#### Code example

```kotlin
storage.list(
  bucketName,
  Storage.BlobListOption.prefix("directory")
)
  .iterateAll()
  .map { it.blobId }
  .let { storage.delete(it) }
```

#### Stack trace
No exceptions thrown

**Comment by athakor** [comment]
@mindtraveller I am not able to reproduced this issue in **java** as well in **kotlin** , please check the below sample which will successfully remove the objects from the `"dir/"` folder.

**Sample**

```javascript
import com.google.cloud.storage.Blob
import com.google.cloud.storage.BlobInfo
import com.google.cloud.storage.Storage
import com.google.cloud.storage.StorageOptions

fun main() {
    val bucket = "bucket-name"
    val directoryName = "dir/"
    val contentType = "text/plain"
    val blobByteContent = byteArrayOf(0xD, 0xE, 0xA, 0xD)
    val storage = StorageOptions.getDefaultInstance().service
    val blobNames = arrayOf(directoryName + "blob 1", directoryName + "blob 2")
    val blob1: BlobInfo = BlobInfo.newBuilder(bucket, blobNames[0]).setContentType(contentType).build()
    val blob2: BlobInfo = BlobInfo.newBuilder(bucket, blobNames[1]).setContentType(contentType).build()
    storage.create(blob1, blobByteContent)
    storage.create(blob2, blobByteContent)

    val iterator: Iterator<Blob> = storage.list(bucket, Storage.BlobListOption.prefix(directoryName)).iterateAll().iterator()
    while (iterator.hasNext()) {
        val blob = iterator.next()
        storage.delete(blob.blobId)
    }
}
```

**Comment by mindtraveller** [comment]
hi @athakor,
what version of lib did you use? I just run your code and it doesn't remove blob 1/2, but removes blobs without whitespace.
