### ISSUE TITLE
Cloud Storage: Application default credentials not working when signing a url

### ISSUE THREAD

**Issue by thestarmaker** [googleapis/java-storage#602]
Hi Guys, 

The README authentication for local development section states:
```
If running locally for development/testing, you can use the Google Cloud SDK. 
Create Application Default Credentials with 'gcloud auth application-default login', and then google-cloud will automatically detect such credentials.
```
When authorising with this method and trying to sign a URL the following exception happens:

```
java.lang.IllegalStateException: Signing key was not provided and could not be derived
	at com.google.common.base.Preconditions.checkState(Preconditions.java:511)
	at com.google.cloud.storage.StorageImpl.signUrl(StorageImpl.java:728)

```

SDK is pretty much saying - ah, you have to be service account to issue signed requests (StorageImpl.java):
```
    if (credentials == null) {
      checkState(
          this.getOptions().getCredentials() instanceof ServiceAccountSigner,
          "Signing key was not provided and could not be derived");
      credentials = (ServiceAccountSigner) this.getOptions().getCredentials();
    }
```

If I activate service account with:
```
gcloud auth activate-service-account my-sa@my-proj.iam.gserviceaccount.com --key-file=<path-to-service-account-credentials-json>
```
then SDK fails to recognise the service account credentials because gcloud adds them to ~/.config/gcloud/legacy_credentials while inside the SDK the "well known location" is ~/.config/gcloud/application_default_credentials.json; but I struggle to find a way to force gcloud to write service account credentials to application_default_credentials.json.

It seems there is no other way to get URL signing working as to use the GOOGLE_APPLICATION_CREDENTIALS but why should this be set if there already is gcloud and everything is already available in ~/.config/gcloud? I would really prefer relying purely on gcloud for this. Am I missing something?

#### Environment details
OS type and version: Ubuntu 20.04.1 LTS
Java version: OpenJDK Runtime Environment Zulu15.28+13-CA (build 15.0.1+8)
google-cloud-java version(s): "com.google.cloud:google-cloud-storage:1.113.2"

**Comment by athakor** [comment]
@thestarmaker 

What `signUrl `does is looking in the credentials you provided to `StorageOptions `for a private key. If you are authenticated with default credentials you provided no private key (because you don't need to) hence the complaint `Signing key not provided.`

To use `signUrl `when authenticated with default credentials you can pass a private key using the `SignUrlOption.serviceAccount` option. See the java doc for [Storage.signUrl](https://github.com/googleapis/java-storage/blob/master/google-cloud-storage/src/main/java/com/google/cloud/storage/Storage.java#L2699-L2809) for more details.

Try below way to do it.

```javascript
// Create ServiceAccountAuthCredentials from a stream
ServiceAccountAuthCredentials credentials = AuthCredentials.createForJson(new FileInputStream("/path/to/key.json"));

// OR from a String (account) and PrivateKey
ServiceAccountAuthCredentials credentials = AuthCredentials.createFor(ACCOUNT, PRIVATE_KEY);

// Create the signed URL
URL url = storage.signUrl(BlobInfo.builder(BUCKET_NAME, OBJECT_NAME).build(), 30,
    TimeUnit.MINUTES, Storage.SignUrlOption.httpMethod(HttpMethod.GET),
    Storage.SignUrlOption.serviceAccount(credentials));
```
Please let us know if this helps!

**Comment by thestarmaker** [comment]
@athakor Thanks for looking into it! Sorry, I am not sure I understand your proposal though. You are pretty much suggesting to not use google auth based credentials  (well known location mechanism) at all and bypass it by selecting key file manually but there are two problems with this:
* when running in GCloud I would rather rely on the container credentials mechanism instead of reading key files manually and I would like this code to be the same in dev and prod.
* the suggestion contradicts what the rest of the documentations is saying (https://cloud.google.com/sdk/gcloud/reference/auth/application-default/login):
```
This command is useful when you are developing code that would normally use a service account but need to run the code in a local development environment where it's easier to provide user credentials. The credentials will apply to all API calls that make use of the Application Default Credentials client library.
```
The above implies that if a service account is capable of signing URLs when running in GCloud the same action should be possible when running locally given I have logged in as that service account.

I would like to be able to login as a particular service account locally and be able to do local development without manually fiddling with key files.

**Comment by frankyn** [comment]
Hi @thestarmaker, apologies for the delay. Are you still having this issue?
