### ISSUE TITLE
Deprecated MD5 hash function

### ISSUE THREAD

**Issue by elharo** [googleapis/java-storage#64]
[WARNING] /home/elharo/java-storage/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java:[149,57] md5() in com.google.common.hash.Hashing has been deprecated
[WARNING] /home/elharo/java-storage/google-cloud-storage/src/main/java/com/google/cloud/storage/StorageImpl.java:[165,57] md5() in com.google.common.hash.Hashing has been deprecated

**Comment by elharo** [comment]
Warning: MD5 is not cryptographically secure or collision-resistant and is not recommended for use in new code. It should be used for legacy compatibility reasons only. Please consider using a hash function in the SHA-2 family of functions (e.g., SHA-256).

**Comment by frankyn** [comment]
The client should turn ignore deprecation warnings. The reason md5 is used for checksum verification of object payloads in GCS. 

Do you have an alternative recommendation @elharo?

Thanks for filing this issue.

**Comment by elharo** [comment]
There are other hash functions. Is this particular algorithm required for compatibility with the server? Or is this something where any hash function will work?

**Comment by frankyn** [comment]
Md5 is used by the service (so is crc32c):
https://cloud.google.com/storage/docs/json_api/v1/objects

Until the service deprecates this metadata field we should continue to support md5 data verification.
