### ISSUE TITLE
Add built-in proxy support

### ISSUE THREAD

**Issue by tooptoop4** [googleapis/java-storage#640]
The current way to access GCS blobs over a corporate proxy is to use System.setProperty. The problem with this approach is that it affects all other connections made from the java app (ie it is a JVM wide property and the user's java app might need to use proxy for GCS connection but no proxy for other https connections such as to internal apps).

AWS currently supports this. ie https://github.com/aws/aws-sdk-java/blob/7b1e5b87b0bf03456df9e77716b14731adf9a7a7/aws-java-sdk-core/src/main/java/com/amazonaws/util/RuntimeHttpUtils.java#L82 using ClientConfiguration.setProxyHost / ClientConfiguration.setProxyPort (https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/ClientConfiguration.html)

**Comment by BenWhitehead** [comment]
I'm not exactly sure how you're wanting to connect to your proxy, but assuming you want to proxy all connections for the storage library you could do something like the following:

```java
    Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 3128));  // TODO: update this config to match your environment and proxy type

    // The following is how you'd plumb the proxy instance into Storage
    NetHttpTransport netHttpTranspor = new NetHttpTransport.Builder()
        .setProxy(proxy)
        .build();
    HttpTransportOptions httpTransportOptions = HttpTransportOptions.newBuilder()
        .setHttpTransportFactory(() -> netHttpTranspor)
        .build();
    StorageOptions storageOptions = StorageOptions.newBuilder()
        .setTransportOptions(httpTransportOptions)
        .build();
    Storage s = storageOptions
        .getService();
```
