### ISSUE TITLE
Wrong HttpStorageRpcSpans.SPAN_NAME_LIST_OBJECTS value?

### ISSUE THREAD

**Issue by mwojterski** [googleapis/java-storage#942]
https://github.com/googleapis/java-storage/blob/5e9906173ade5434ce1cecbd920445494b375652/google-cloud-storage/src/main/java/com/google/cloud/storage/spi/v1/HttpStorageRpcSpans.java#L30

**Comment by BenWhitehead** [comment]
Thanks for bringing this to our attention, I'll consult with some folks and hopefully have a fix.
