### ISSUE TITLE
Support cloud storage range get

### ISSUE THREAD

**Issue by hrchu** [googleapis/java-storage#945]
google cloud storage json api supports the range header: https://cloud.google.com/storage/docs/json_api/v1/parameters#range

But there is no way to specify it in Java SDK.

This feature is essential for retrieving only part of the object data, e.g., 1 byte of 5TB, without downloading the whole file content.

**Comment by danielduhh** [comment]
Fixed by https://github.com/googleapis/java-storage/pull/1324
