### ISSUE TITLE
Storage: storage.get triggers an error: java.lang.NoSuchMethodError: com.google.api.services.storage.model.StorageObject.getCustomTime()

### ISSUE THREAD

**Issue by onetwopunch** [googleapis/java-storage#994]
#### Environment details

1. OS type and version: MacOSX
2. Java version: 11
3. storage version(s): 2.1.0

#### Code example

```java
private Blob doCopy(String filename) {
  BlobId srcId = BlobId.fromGsUtilUri(filename);
  Blob src = this.storage.get(srcId); // <--- This line triggers the error
  CopyWriter w = src.copyTo(this.destBucket, this.destObject);
  return w.getResult();
}
```

#### Stack trace
```
Caused by: java.lang.NoSuchMethodError: com.google.api.services.storage.model.StorageObject.getCustomTime()Lcom/google/api/client/util/DateTime;
    at com.google.cloud.storage.BlobInfo.fromPb (BlobInfo.java:1212)
    at com.google.cloud.storage.Blob.fromPb (Blob.java:972)
    at com.google.cloud.storage.StorageImpl.get (StorageImpl.java:330)
    at com.google.cloud.storage.StorageImpl.get (StorageImpl.java:338)
    at com.myorg.myapp.MatchKeywordsDoFn.doCopy (MatchKeywordsDoFn.java:65)
    at com.myorg.myapp.MatchKeywordsDoFn.processElement (MatchKeywordsDoFn.java:52)
```

#### External references such as API reference guides

- https://googleapis.dev/java/google-cloud-storage/latest/com/google/cloud/storage/Blob.html#copyTo-java.lang.String-com.google.cloud.storage.Blob.BlobSourceOption...-

#### Any additional information below

I'm not sure this makes a difference but I'm running this as part of an Apache Beam pipeline.

**Comment by onetwopunch** [comment]
To add another example, I also tried copy using the `CopyRequest` class per the example [here](https://googleapis.dev/java/google-cloud-storage/latest/com/google/cloud/storage/Storage.html#copy-com.google.cloud.storage.Storage.CopyRequest-) with the same result just from the `getResult()` function. 

**Source**
```java
private Blob doCopy(String filename) {
    BlobId srcId = BlobId.fromGsUtilUri(filename);
    Storage.CopyRequest req = Storage.CopyRequest.newBuilder().setSource(srcId)
      .setTarget(BlobId.of(this.destBucket, this.destObject))
      .build();
    return this.storage.copy(req).getResult(); // <--- This line triggers the error
}
```

**Error**
```
Caused by: java.lang.NoSuchMethodError: com.google.api.services.storage.model.StorageObject.getCustomTime()Lcom/google/api/client/util/DateTime;
    at com.google.cloud.storage.BlobInfo.fromPb (BlobInfo.java:1212)
    at com.google.cloud.storage.Blob.fromPb (Blob.java:972)
    at com.google.cloud.storage.CopyWriter.getResult (CopyWriter.java:77)
    at com.myorg.myapp.MatchKeywordsDoFn.doCopy (MatchKeywordsDoFn.java:68)
    at com.myorg.myapp.MatchKeywordsDoFn.processElement (MatchKeywordsDoFn.java:52)
```

**Comment by BenWhitehead** [comment]
Hi @onetwopunch this sounds like there is a "bad" version of `com.google.apis:google-api-services-storage` that is being picked up at runtime.

`com.google.cloud:google-cloud-storage:2.1.0` is built against `com.google.apis:google-api-services-storage:v1-rev20210127-1.32.1`.

Can you verify which version you're using?

If you're using maven you can find out by running the following command:
```sh
mvn dependency:tree -Dincludes=com.google.apis:google-api-services-storage
```

**Comment by onetwopunch** [comment]
Ahh interesting, that would make sense

```
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ myapp ---
[INFO] com.myorg.myapp:jar:1.0-SNAPSHOT
[INFO] \- org.apache.beam:beam-sdks-java-extensions-google-cloud-platform-core:jar:2.21.0:compile
[INFO]    \- com.google.apis:google-api-services-storage:jar:v1-rev20191011-1.30.3:compile
```

I'm fairly new to Maven and Java in general, how would I bump the version of api-services in my `pom.xml` or otherwise?

**Comment by onetwopunch** [comment]
Welp, it turns out that since `google-api-services-storage` is brought in by Beam, I just needed to update Beam from `2.21.0` to `2.29.0` and now things work as expected. Java dependency management is weird.

**Comment by BenWhitehead** [comment]
haha, thanks for reporting back @onetwopunch. I was actually working on writing up the options of how you might be able to proceed (one of which would be to update beam).

Glad you were able to get unblocked, and that updating beam was possible for you.
